<?php
use Orchestra\Testbench\TestCase as BaseTestCase ;

class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    protected function getPackageProviders($app)
    {
        return [
          \Moh3n\LaravelMedia\LaravelMediaServiceProvider::class
        ];
    }
}